Enabled various gaming protocols: T102, ATCP, GMCP
kruton/tinyfugue pull request #16
Opened 2021-06-24 21:23 UTC by warmstarter

Straight-forward patch to add support for three MUD / MOO related protocols. These default to off, but wouldn't be a problem to have them defaulting to on.

2021-06-24 21:39 UTC, kruton commented
Looks like `configure.orig` is accidental.

2021-06-24 23:34 UTC, warmstarter commented
Woops, you're right. Got rid of that and updated the .gitignore

2021-06-25 04:36 UTC, kruton requested changes

2021-06-25 04:36 UTC, kruton commented on src/socket.c
> +		    (rawchar == TN_102 && 102) ||
`&& 102` will never be false, but it looks like this should have been `&& option102`.

2021-06-25 16:04 UTC, kruton approved these changes

2021-06-25 16:05 UTC, merged